name: R-CMD-check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # see https://github.com/r-lib/actions/tree/master/examples
  R-CMD-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@master
    - name: Install dependencies
      run: |
        install.packages(c("remotes", "rcmdcheck"))
        remotes::install_deps(dependencies = TRUE)
      shell: Rscript {0}
    - name: Check
      run: rcmdcheck::rcmdcheck(error_on = "note")
      shell: Rscript {0}
 
